### ISSUE TITLE
Add ndt7 as a new experiment name

### ISSUE THREAD

**Issue by bassosimone** [m-lab/mlab-ns#188]
@stephen-soltesz will help me to do that.

Here's what needs to be done:

- [x] prometheus monitoring for ndt7
    - [x] black box exporter checking of port 443
    - [x] lame duck check 
    - [x] https://github.com/m-lab/operator/blob/master/generate_prometheus_targets.sh#L87 & ipv6
    - [x] https://github.com/m-lab/prometheus-support/blob/master/k8s/prometheus-federation/deployments/prometheus.yml#L136
- [x] ndt7 endpoint in mlab-ns
    - [x] new tool type
        - [x] tools.csv new line?
        - [x] When is tools.csv deployed?
    - [x] new prometheus status queries for ndt7 and ndt7_ipv6
        - [x] uses the monitoring from the previous step - https://github.com/m-lab/mlab-ns/blob/master/server/mlabns/util/prometheus_status.py#L31
- [x] add forwarding of that ndt7 endpoint to staging for now
    - [x] ndt_ssl & probability
    - [x] ndt7 & probability
    - [x] https://github.com/m-lab/mlab-ns/blob/master/server/mlabns/util/reverse_proxy.py#L17

**Comment by bassosimone** [comment]
I've discussed this with @stephen-soltesz and it seems I am becoming a bottleneck so we have concluded that perhaps it's better if @evfirerob could help in this task.

**Comment by stephen-soltesz** [comment]
@evfirerob you asked about the probability reverse proxy feature this morning. The main idea is to make check for the valid paths we would consider here, i.e. ndt_ssl & ndt7:

* https://github.com/m-lab/mlab-ns/blob/master/server/mlabns/util/reverse_proxy.py#L65

Then make `get_reverse_proxy` accept a parameter, probably the name of the target path:

* https://github.com/m-lab/mlab-ns/blob/master/server/mlabns/util/reverse_proxy.py#L17

So, instead of a single 'default' model.ReverseProxyProbability there would be one for each supported target. We would leave the value for ndt_ssl as-is, but in production we could initially set the one for ndt7 to 1.0 so that all requests to the prod instance of ndt7 return healthy mlab4s. -- As we upgrade more of the prod fleet, we can adjust the probability until it looks more like ndt_ssl.

**Comment by evfirerob** [comment]
@stephen-soltesz I'm picking this up again today and I'll let you know if I have more questions, thank you!

**Comment by evfirerob** [comment]
The `/ndt7` endpoint is now available on staging. I've replaced the `default` probability on Datastore with two entities, one for `ndt_ssl` and one for `ndt7`, both with `probability=0`.

**Comment by bassosimone** [comment]
Thanks a bunch for working on this!

**Comment by bassosimone** [comment]
This is now done thanks to @evfirerob and @stephen-soltesz who made it possible! 🙏
